### ISSUE TITLE
Seed Phrase Display Issue

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-android-wallet#163] opened 2020-06-11 22:39 UTC
On wallet versions based on commit `e4d060d` the final word of seed phrase display is truncated by exactly two letters. The seed is correct behind the scenes, but the UI is incorrect and could cause people to backup the wrong seed phrase.

I tested that the seed is correct and that our checksum on the seed phrase does indeed catch if an incorrect seed phrase is entered, but it could still lead to issues upon backup and reimport for a user that doesn't understand.

**Comment by gmale** [comment] 2020-06-12 00:31
Corrected in the related library https://github.com/zcash/kotlin-bip39/pull/2 and added a test to reproduce the problem. Then, verified that it went from failing to passing.

The root issue was that the final iteration [counted in the wrong direction]( https://github.com/zcash/kotlin-bip39/pull/2/files#diff-17b9fe90f3f97debf3fd58652ccd2ba6L75). So this shortened the last word because we need to account for the lack of a space at the very end by shifting `i` ahead by one.

This function is only used when displaying the words so (thankfully) it did not impact the seed that gets generated. It's just that when the wallet shows the seed phrase to the user, it would appear truncated by two characters.

In the absolute worst case this might lead the user to write down the wrong 24th seed word but that word is determined by the checksum so it would be easy to recover.

**Comment by gmale** [comment] 2020-06-12 00:32
This issue has been corrected in https://github.com/zcash/zcash-android-wallet/pull/164. Resolving this issue.

**Closed by gmale** 2020-06-12 00:32 UTC
